name: Build APK

on:
  workflow_dispatch:   # 手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip git zip unzip openjdk-17-jdk liblzma-dev
        pip install --upgrade pip
        pip install buildozer

    - name: Init buildozer if not exists
      run: |
        if [ ! -f buildozer.spec ]; then
          buildozer init
        fi

    - name: Run buildozer
      run: |
        buildozer android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: app-apk
        path: bin/*.apk
